### ISSUE TITLE
All values are always nil even if locals are being passed

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#25]
Tests are passing (including this feature), but on a starter Bullet Train app `created_at` & `updated_at` fields don't have `format: date-time` option.

**Comment by kaspth** [comment]
What format are they set to, just `format: time`? I remember having trouble with this too where either Ruby or Rails' time zone info isn't set, so Rails won't cast to `ActiveSupport::TimeWithZone` instances and the behavior doesn't fire.

**Comment by kaspth** [comment]
Here we go, this is what I was thinking of: https://github.com/bullet-train-co/jbuilder-schema/blob/0991a6b7dd7f0f8c546e2006ef3f171a9d5fc5f2/test/setup/active_record.rb#L5-L8

**Comment by newstler** [comment]
It seems the problem is that for defining types jbuilder-schema uses model definitions where all values are nil, instead of real object with values being set so it's possible to know what is what. That's why there's no `format` for timestamps, as well as any integer field (including `id`) is always set to string (as `nil` being casted as string).

If I create real values right in jbuilder, everything works as expected:
```
json.test_time Time.now
json.test_date Date.today
json.test_datetime DateTime.now
json.test_time_with_zone Time.zone.now
```
produces
```
                test_time:
                    type: string
                    format: time
                    description: "translation missing: en.teams.fields.test_time.heading"
                test_date:
                    type: string
                    format: date
                    description: "translation missing: en.teams.fields.test_date.heading"
                test_datetime:
                    type: string
                    format: date-time
                    description: "translation missing: en.teams.fields.test_datetime.heading"
                test_time_with_zone:
                    type: string
                    format: date-time
                    description: "translation missing: en.teams.fields.test_time_with_zone.heading"
```

I tried to dig up the code and understand why we don't use real object, even if passed into `locals` (`Jbuilder::Schema.renderer(paths, locals: { team: Team.create(name: "Test") })`), but no luck. Need your help here, @kaspth :)
