### ISSUE TITLE
Object partials are being set as strings

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#48]
If we have 
```ruby
json.author article.user, partial: "api/v1/users/user", as: :user
```
The output is
```yaml
  author:
    type:
    - string
    - 'null'
    description: test
```
But it has to be
```yaml
  author:
    type:
    - object
    - 'null'
    "$ref": "#/components/schemas/user"
    description: test
```
---
If we set partial in a block:
```ruby
json.contact do
  json.partial! 'api/v1/contacts/contact', contact: project.contact
end
```
then the result is right:
```yaml
                contact:
                    type:
                        - object
                        - "null"
                    "$ref": "#/components/schemas/contact"
                    description: "Translation missing: en.projects.fields.contact.heading"
```
But if set them in inline format:
```ruby
json.contact project.contact, partial: "api/v1/contacts/contact", as: :contact
```
then the result is:
```yaml
                contact:
                    type:
                        - string
                        - "null"
                    description: "Translation missing: en.projects.fields.contact.heading"
```
