### ISSUE TITLE
`json.array!`'s `items` is generated wrong when it is not a reference

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#51]
It would be convenient to add a custom version of that partial that is local to the template being rendered (for example, in `orders/_order.json.jbuilder` we want to inline just `:id` and `:name` of the segments.
Currently we have

```ruby
json.segments do
  json.array! order.workspace&.segments do |segment|
    json.id segment.id
    json.name segment.name
  end
end
```
Which results in invalid OpenAPI schema of
```yaml
segments:
  type:
  - array
  - 'null'
  items: []
  description: Segments
```
(where the `items: []` is invalid since it either expects a `$ref` or the properties to be listed)

Having a `orders/_segment.json.jbuilder` template that we could include with
```ruby
json.segments order.workspace&.segments, partial: "api/v2/orders/segment", as: :segment
```
might be better to be able to include those properties?

**Comment by newstler** [comment]
**Look why `items` array is empty.**

**Comment by newstler** [comment]
Also sometimes arrays do not have object root attributes:
```ruby
json.goals_many_lines do
  json.array! project.goals do |goal|
    json.partial! "api/v1/shared/id", resource: goal
    json.extract! goal, :description
  end
end
```
produces
```yaml
                goals_many_lines:
                    type: array
                    items:
                        id:
                            type: integer
                            description: Project ID
                        public_id:
                            type: string
                            description: "Translation missing: en.projects.fields.public_id.heading"
                        description:
                            type: string
                            description: "Translation missing: en.projects.fields.description.heading"
                    description: "Translation missing: en.projects.fields.goals_many_lines.heading"
                    nullable: true
```
but should
```yaml
                goals_many_lines:
                    type: array
                    items:
                        type: object
                        title: Projects
                        description: Projects
                        required:
                            - id
                        properties:
                            id:
                                type: integer
                                description: Project ID
                            public_id:
                                type: string
                                description: "Translation missing: en.projects.fields.public_id.heading"
                            description:
                                type: string
                                description: "Translation missing: en.projects.fields.description.heading"
                    description: "Translation missing: en.projects.fields.goals_many_lines.heading"
                    nullable: true
```

**Comment by newstler** [comment]
Also multiline arrays have wrong `title` and `description`:
```ruby
json.contact_many_lines do
  json.partial! "api/v1/shared/id", resource: project.contact
  json.extract! project.contact, :address
end
```
produces
```yaml
                contact_many_lines:
                    type: object
                    title: Projects
                    description: Projects
                    required:
                        - id
                    properties:
                        id:
                            type: integer
                            description: Project ID
                        public_id:
                            type: string
                            description: "Translation missing: en.projects.fields.public_id.heading"
                            nullable: true
                        address:
                            type: string
                            description: "Translation missing: en.projects.fields.address.heading"
                            nullable: true
                    nullable: true
```
but should
```yaml
                contact_many_lines:
                    type: object
                    title: Contact
                    description: Contact
                    required:
                        - id
                    properties:
                        id:
                            type: integer
                            description: Project ID
                        public_id:
                            type: string
                            description: "Translation missing: en.projects.fields.public_id.heading"
                            nullable: true
                        address:
                            type: string
                            description: "Translation missing: en.projects.fields.address.heading"
                            nullable: true
                    nullable: true
```
This can be fixed by:
```ruby
json.contact_many_lines schema: {object: project.contact} do
```
