### ISSUE TITLE
Shared partial breaks doc generation

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#52]
https://github.com/clickfunnels2/admin/pull/20857

Here we trying to add additional attributes into all templates by adding a shared partial - which breaks doc gen with `ArgumentError: unknown keyword: :resource`

**Comment by newstler** [comment]
It appears constructions like
```ruby
json.partial! "api/v1/shared/id", resource: team
json.partial! "api/v1/shared/id", locals: {resource: team}
etc.
```
are not yet supported.

**Comment by newstler** [comment]
Current progress:

- Found a way to tell if `partial!` is called within a block or not
- Made the partial out of block generate common attributes instead of `$ref`
- When `partial!` is used inside the block, but together with other attributes, like:
```ruby
json.contact do
  json.partial! "api/v1/shared/id", resource: project.contact
  json.extract! project.contact, :address
end
```
it generates the right output with attributes being listed inside the object:
```yaml
                contact:
                    type:
                        - object
                        - "null"
                    title: Projects
                    description: Projects
                    required:
                        - id
                    properties:
                        id:
                            type: integer
                            description: Project ID
                        public_id:
                            type:
                                - string
                                - "null"
                            description: "Translation missing: en.projects.fields.public_id.heading"
                        address:
                            type:
                                - string
                                - "null"
                            description: "Translation missing: en.projects.fields.address.heading"
```

So technically the problem from the linked issue is solved. Nevertheless:

- When `partial!` is used inside the array block, but together with other attributes, like:
```ruby
json.goals do
  json.array! project.goals do |goal|
    json.partial! "api/v1/shared/id", resource: goal
    json.extract! goal, :description
  end
end
```
the output doesn't contain the object wrapper:
```yaml
                goals:
                    type:
                        - array
                        - "null"
                    items:
                        id:
                            type: integer
                            description: Project ID
                        public_id:
                            type: string
                            description: "Translation missing: en.projects.fields.public_id.heading"
                        description:
                            type: string
                            description: "Translation missing: en.projects.fields.description.heading"
                    description: "Translation missing: en.projects.fields.goals.heading"
```
- Comments in partials break the code
- No tests
- Found that simple array with objects `json.arr [{a: 1, b: 2}, {c:3, r:4}]` produces strings (create new issue!):
```yaml
                arr:
                    type:
                        - array
                        - "null"
                    minContains: 0
                    contains:
                        type: string
                    description: "Translation missing: en.projects.fields.arr.heading"
```
