### ISSUE TITLE
Wrong type in array's `contains` for objects

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#60]
Simple array with objects like `json.arr [{a: 1, b: 2}, {c:3, r:4}]` produce strings in `contains`:
```yaml
                arr:
                    type:
                        - array
                        - "null"
                    minContains: 0
                    contains:
                        type: string
                    description: "Translation missing: en.projects.fields.arr.heading"
```
