### ISSUE TITLE
`format` in dates disappeared

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#72]
```yaml
                created_at:
                    type:
                        - string
                        - "null"
                    description: Signed Up At
```
should be:
```yaml
                created_at:
                    type:
                        - string
                        - "null"
                    **format: date-time**
                    description: Signed Up At
```
