### ISSUE TITLE
Wrong translations scope with `/` in it

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#83]
````yaml
        tags:
          type:
          - array
          - 'null'
          items:
            type: object
            title: 'Translation missing: en.contacts/tags.title'
            description: 'Translation missing: en.contacts/tags.heading'
            required:
            - id
            - name
            - color
            properties:
              id:
                type: integer
                description: Tag ID
              name:
                type: string
                description: Name
              color:
                type: string
                description: Color
          title: 'Translation missing: en.en.contacts.tags.heading'
          description: 'Translation missing: en.contacts/tags.fields.tags.heading'
````
